[phases.setup]
nixPkgs = ["ffmpeg", "pkg-config", "bash"]

[phases.build]
cmd = '''
  echo "🔧 Building application..."
  go version
  go build -o out .
  chmod +x start.sh
'''

[start]
cmd = "./start.sh"
